version: '3.8'

services:
  backend:
    build:
      context: ./backend/chamadoapp
    container_name: chamado-backend
    ports:
      - "8080:8080"
    networks:
      - chamado-net
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/chamado-frontend
    container_name: chamado-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - chamado-net

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: chamadosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gt@19a01
    ports:
      - "5432:5432"
    networks:
      - chamado-net

networks:
  chamado-net:
    driver: bridge